name: difforge-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
    - ipykernel==6.29.5
    - jupyter==1.1.1
    - matplotlib==3.10.0
    - numpy==2.2.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - sentence-transformers==3.4.1
    - torch==2.6.0